# Generated by Django 3.1.7 on 2021-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=191, unique=True)),
                ('city', models.CharField(max_length=191, null=True)),
                ('state', models.CharField(max_length=191, null=True)),
                ('country', models.CharField(max_length=191, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'orion_branch',
                'ordering': ['-id'],
            },
        ),
    ]
